=== Megustaelkebab/Projecte-T1--Part1-XML-DTD/ProjecteT1-P1-DJM.dtd
<?xml version="1.0" encoding="UTF-8"?>

        <!ELEMENT PHASMOPHOBIA (fantasma+,mapa+)>
        <!ELEMENT fantasma (proba1, proba2, proba3, descripcio_f,timid?,foto_f)>
        <!ATTLIST fantasma
                id ID #REQUIRED
                nom CDATA #REQUIRED
                fecha_introduccio CDATA #REQUIRED
                velocitat (lenta | normal | alta) #REQUIRED
                cordura_caÃ§ar (molt_prompte| prompte| normal |tard)
                >

        <!ELEMENT proba1 (#PCDATA)>
        <!ELEMENT proba2 (#PCDATA)>
        <!ELEMENT proba3 (#PCDATA)>
        <!ELEMENT descripcio_f (#PCDATA)>
        <!ELEMENT timid (#PCDATA)>
        <!ELEMENT foto_f (#PCDATA)>


        <!ELEMENT mapa (descripcio_m,fusible,posesio_maldita?,foto_m)>
        <!ATTLIST mapa
                id ID #REQUIRED
                nom CDATA #REQUIRED
                tamany (xicotet | mitja | gran | enorme) #REQUIRED
                fecha_introduccio CDATA #REQUIRED
                obert (si | no) "no"
                >

        <!ELEMENT descripcio_m (#PCDATA)>
        <!ELEMENT fusible (#PCDATA)>
        <!ELEMENT posesio_maldita (#PCDATA)>
        <!ELEMENT foto_m (#PCDATA)>

=== Megustaelkebab/Projecte-T1--Part1-XML-DTD/ProjecteT1-P1-DJM.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PHASMOPHOBIA SYSTEM "ProjecteT1-P1-DJM.dtd">

<PHASMOPHOBIA>
    <fantasma id="f1"  nom="Poltergeist" fecha_introduccio="18/9/2020" velocitat="normal" cordura_caçar="normal">
        <proba1>Escritura</proba1>
        <proba2>Ultravioleta</proba2>
        <proba3>Temperatura</proba3>
        <descripcio_f>El Poltergeist es un esperit entremaliat que pot manipular diversos objectes al mateix temps.</descripcio_f>
        <foto_f>fotos_projecte/poltergeist.jpg</foto_f>
    </fantasma>

    <fantasma id="f2" nom="Jinn" fecha_introduccio="18/9/2020" velocitat="alta" cordura_caçar="tard">
        <proba1>EMF5</proba1>
        <proba2>Temperatura</proba2>
        <proba3>Orbes</proba3>
        <descripcio_f>El Jinn es molt rapid i ataca si es sent amenaçat.</descripcio_f>
        <timid>si</timid>
        <foto_f>fotos_projecte/jinn.jpg</foto_f>
    </fantasma>

    <fantasma id="f3" nom="Pesadilla" fecha_introduccio="03/12/2020" velocitat="lenta" cordura_caçar="molt_prompte">
        <proba1>Orbes</proba1>
        <proba2>Escritura</proba2>
        <proba3>Temperatura</proba3>
        <descripcio_f>La pesadilla prefereix la foscor i es mes agressiva quan les llums estan apagades.</descripcio_f>
        <foto_f>fotos_projecte/pesadilla.jpg</foto_f>
    </fantasma>

    <fantasma id="f4" nom="Revenant" fecha_introduccio="18/9/2020" velocitat="lenta" cordura_caçar="prompte">
        <proba1>DOTS</proba1>
        <proba2>Escritura</proba2>
        <proba3>Orbes</proba3>
        <descripcio_f>El Revenant es molt lent quan no esta perseguint, pero rapid quan segueix a la victima.</descripcio_f>
        <foto_f>fotos_projecte/revenant.jpg</foto_f>
    </fantasma>
    
    <fantasma id="f5" nom="Oni" fecha_introduccio="16/05/2021" velocitat="normal" cordura_caçar="molt_prompte">
        <proba1>EMF</proba1>
        <proba2>DOTs</proba2>
        <proba3>Temperatura</proba3>
        <descripcio_f>Als Onis els encanta espantar a les seues víctimes tant com siga possible abans d'atacar. Sovint se'ls veu en la seua forma física, custodiant el seu lloc de mort. Seran molt mes agressius quantes més persones s'acosten al seu territori</descripcio_f>
        <foto_f>fotos-projecte/oni.jpg</foto_f>
    </fantasma>

    <mapa id="m1" nom="Casa de Tanglewood" tamany="xicotet" fecha_introduccio="18/9/2020" obert="no">
        <descripcio_m>Una casa xicoteta i acollidora amb un toc de terror, ideal per a investigacions inicials.</descripcio_m>
        <fusible>Soterrani</fusible>
         <posesio_maldita>Cercle d'invocació</posesio_maldita>
        <foto_m>fotos-projecte/tanglewood.jpg</foto_m>
    </mapa>

    <mapa id="m2" nom= "Campament Maple Lodge" tamany="gran" fecha_introduccio="27/10/2023" obert="si">
        <descripcio_m>Un gran campament amb multiples tendes de campanya y una gran casa prop del llac.Este campament proposarà un veritable desafiament a aquells caça fantasmes que s'atrevisquen a plantar cara a les històries que turmenten este paranormal parc natural .</descripcio_m>
        <fusible>Quart de manteniment</fusible>
        <posesio_maldita>Ninot vudú</posesio_maldita>
        <foto_m>fotos-projecte/maple_lodge.jpg</foto_m>
    </mapa>

    <mapa id="m3" nom="Granja de Grafton" tamany="mitja" fecha_introduccio="18/9/2020" obert="no">
        <descripcio_m>Una granja rustica on sovint es donen fenomens paranormals.Seran les almes dels anteriors granjers....</descripcio_m>
        <fusible>Soterrani</fusible>
        <posesio_maldita>Espill maleit</posesio_maldita>
        <foto_m>fotos_projecte/grafton.jpg</foto_m>
    </mapa>

    <mapa id="m4" nom="Preso" tamany="enorme" fecha_introduccio="03/12/2020" obert="si">
        <descripcio_m>Una preso abandonada amb amplis espais oberts i cel·les per explorar. Diuen que aquells presos que van morir aci busquen venjança i no dubtaran en atacar a tots aquells que s'atrevisquen a entrar en el seu territori</descripcio_m>
        <fusible>Oficina de seguretat</fusible>
        <posesio_maldita>Ouija</posesio_maldita>
        <foto_m>fotos-projecte/prisio.jpg</foto_m>
    </mapa>
    
    <mapa id="m5" nom="nº13 Willow Street" tamany="xicotet" fecha_introduccio="18/07/2022" obert="no">
        <descripcio_m>Una nova casa acabada de construir i amb pocs amagatalls. Ideal per a caçar fantasmes experimentats! Els informes diuen que va ser construïda sobre una cosa sobrenatural, tal vegada un cementeri...</descripcio_m>
        <fusible>Soterrani</fusible>
        <posesio_maldita>Má de mico</posesio_maldita>
        <foto_m>fotos-projecte/willow.jpg</foto_m>
    </mapa>
</PHASMOPHOBIA>
